### PR TITLE
Remove errant whitespace

### PR DESCRIPTION
**Pull request by shaug**
A gem this beautiful shouldn't be marred with misaligned code. :)

### CODE REVIEW

**Comment by deanputney** [comment]
At least make a functional improvement in your commit, you bum! :hankey:

**Comment by shaug** [comment]
Functionally it is pristine? How could I improve on something so sublime?

**Comment by shaug** [comment]
Plus you're always telling me to keep the formatting changes separate from the functional ones. So don't be throwing :hankey: at me when I'm just following your own guidelines.

**Comment by deanputney** [comment]
Someone has to keep your rampant pedantry in check!

Dean

**Comment by kerrizor** [comment]
18 months later...

**Pull request merged**
